services:
  # FastAPI приложение
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Ждем, пока БД будет готова
      minio:
        condition: service_started
    volumes:
      - ./app:/app/app # Для разработки: изменения в коде сразу видны в контейнере
    networks:
      - app-network

  # База данных PostgreSQL
  db:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5442:5432" # Открываем порт наружу для удобства отладки
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Хранилище MinIO
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Веб-консоль
    volumes:
      - minio_data:/data
    networks:
      - app-network

  # MinIO Client для конфигурации
  mc:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
        echo '⏳ Waiting for MinIO...';
        until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          echo '... MinIO still not ready, waiting for 2s';
          sleep 2;
        done;
        echo '✅ MinIO is awailable, craeting bucket...';
        mc mb -p local/${MINIO_BUCKET} || true;
        mc anonymous set download local/${MINIO_BUCKET} || true; # загрузка по прямой ссылке
        echo '✅ Bucket is ready!';
        exit 0;
      "

volumes:
  postgres_data:
  minio_data:

networks:
  app-network:
    external: true
    name: pixelplayer_app-network
