[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["app"]
known_third_party = ["fastapi", "pydantic", "minio", "requests", "zipfile"]
